---
- name: get janus install script
  get_url:
    url: https://raw.githubusercontent.com/carlhuda/janus/master/bootstrap.sh
    dest: /tmp/janus.sh
    mode: "0755"
    force: yes

- name: install janus
  shell: /tmp/janus.sh
  args:
    executable: /bin/bash

- name: install my janus config
  git:
    repo: git@github.com:rnagle/janus.git
    dest: "{{ lookup('env', 'HOME') }}/.janus"
    clone: yes
    track_submodules: yes

- name: set up vimrc symlinks
  file:
    src: "{{ lookup('env', 'HOME') }}/.janus/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.{{ item }}"
    state: link
  with_items:
    - "vimrc.after"
    - "gvimrc.after"

- name: get meslo powerline fonts
  get_url:
    url: "https://github.com/powerline/fonts/raw/master/Meslo%20Dotted/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/Library/Fonts/{{ item }}"
  with_items:
    - "Meslo%20LG%20L%20DZ%20Regular%20for%20Powerline.ttf"
    - "Meslo%20LG%20M%20DZ%20Regular%20for%20Powerline.ttf"
    - "Meslo%20LG%20S%20DZ%20Regular%20for%20Powerline.ttf"

- name: install js and json linters
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - jscs
    - jsonlint

- name: create ~/.config directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory

- name: set up flake8 config
  file:
    src: "{{ lookup('env', 'HOME') }}/.janus/config/flake8"
    dest: "{{ lookup('env', 'HOME') }}/.config/flake8"
    state: link
