---
- name: check for brew
  stat:
    path: "/usr/local/bin/brew"
  register: brew_check

- name: install brew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not brew_check.stat.exists

- homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - gnupg2
    - mysql
    - postgresql
    - postgis
    - awscli
    - ack
    - nginx
    - python
    - wget
    - redis
    - memcached
    - rbenv
    - go
    - node
    - git
    - ctags-exuberant
    - flake8
    - youtube-dl
