---
- name: check for brew
  stat:
    path: "/usr/local/bin/brew"
  register: brew_check

- name: install brew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not brew_check.stat.exists

- homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - gnupg2
    - awscli
    - ack
    - python
    - wget
    - rbenv
    - go
    - node
    - git
    - ctags-exuberant
    - flake8
    - macvim
    - terraform
    - docker
    - pinentry
    - jq

- homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - google-chrome
    - dropbox
    - hipchat
    - vagrant
    - virtualbox
    - slack
    - keybase
    - docker
    - gpgtools
