---
- homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql
    - postgresql
    - postgis
    - awscli
    - ack
    - nginx
    - python
    - wget
    - redis
    - memcached
    - rbenv
    - go
    - node
    - git
    - macvim
    - ctags-exuberant
    - flake8
