---
- name: copy ssh config
  copy:
    src: files/ssh/config
    dest: ~/.ssh/config
    mode: 0644

- name: copy private key
  copy:
    src: files/ssh/id_rsa
    dest: ~/.ssh/id_rsa
    mode: 0600

- name: copy public key
  copy:
    src: files/ssh/id_rsa.pub
    dest: ~/.ssh/id_rsa.pub
    mode: 0600
